apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: huly
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi