apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace
  namespace: huly
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      version: 1.2.8
      sourceRef:
        kind: HelmRepository
        name: polymorphic
        namespace: flux-system
  interval: 10m0s
  values:
    services:
    - name: workspace
      image:
        repository: hardcoreeng/workspace
        tag: v0.6.295 #latest
      healthcheck:
        enabled: false
      env: 
        - name: ACCOUNTS_URL
          # value: "huly-account-svc.huly.svc.cluster.local"
          value: "http://account.huly.example/" #given DNS name
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_ENDPOINT
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: MODEL_ENABLED
          value: "*"
        - name: MONGO_URL
          # value: "huly-mongodb-svc.huly.svc.cluster.local" #need to check
          # value: "mongodb://mongodb:27017" #given DNS name
          value: "mongodb://huly-mongodb-svc:27017"
        - name: DB_URL
          # value: "mongodb://mongodb:27017"
          value: "mongodb://huly-mongodb-svc:27017"
        - name: SERVER_SECRET
          value: "secret"
        - name: TRANSACTOR_URL
          # value: "ws://transactor:3333;ws://localhost:3333" #need to check
          value: "ws://huly-transactor-svc:3333;ws://localhost:3333"
        - name: NOTIFY_INBOX_ONLY
          value: "true"