---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  interval: 10m0s
  values:
    admin:
      existingSecret: grafana
      userKey: admin-user
      passwordKey: admin-password
    persistence:
      enabled: true
      storageClassName: local-path
      size: 2Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      path: /
      pathType: Prefix
      hosts:
        - grafana.pride.improwised.dev
