apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: grafana
stringData:
  admin-user: admin # required field for kubernetes.io/basic-auth
  admin-password: ph16ofun6swupi5rabrlrihoswuswusu # required field for kubernetes.io/basic-auth
