apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-app
  namespace: photoprism
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      version: 1.2.8
      sourceRef:
        kind: HelmRepository
        name: polymorphic
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: photoprism/photoprism
      tag: "231128"
      pullPolicy: IfNotPresent
    envFrom:
      - configMapRef:
          name: photoprism
      - secretRef:
          name: photoprism-app


    services:
    - name: photoprism-svc
      type: StatefulSet
      ports:
      - name: http
        containerPort: 2342
      healthcheck:
        enabled: false
      service:
        enabled: true
        ports:
        - port: 2342
          targetPort: http
          name: http
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
      # ingress:
      #   enabled: false
      #   className: "nginx"
      #   hosts:
      #     - host: photos.pride.improwised.dev
      #       paths:
      #       - path: /
      #         pathType: Prefix
      #         servicePort: 2342
      volumeMounts:
      - name: originals
        mountPath: /photoprism/originals
        # subPath: photos/family
      - name: storage
        mountPath: /photoprism/storage
      - name: imports
        mountPath: /photoprism/import
      volumeClaimTemplates:
      - metadata:
          name: originals
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi
      - metadata:
          name: storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi
      - metadata:
          name: imports
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 1Gi