---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism
  namespace: photoprism
data:
  PHOTOPRISM_ADMIN_USER: "admin"
  PHOTOPRISM_AUTH_MODE: "public"
  PHOTOPRISM_SITE_URL: "http://photoprism.me:2342/"
  PHOTOPRISM_DATABASE_DRIVER: "mysql"
  PHOTOPRISM_DATABASE_SERVER: "photoprism-mariadb.photoprism.svc.cluster.local:3306"
  PHOTOPRISM_DATABASE_NAME: "photoprism"
  PHOTOPRISM_DATABASE_USER: "photoprism"
  PHOTOPRISM_ORIGINALS_LIMIT: "5000"
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: "info"
  PHOTOPRISM_READONLY: "false"
  PHOTOPRISM_EXPERIMENTAL: "false"
  PHOTOPRISM_DISABLE_CHOWN: "false"
  PHOTOPRISM_DISABLE_WEBDAV: "false"
  PHOTOPRISM_DISABLE_SETTINGS: "false"
  PHOTOPRISM_DISABLE_TENSORFLOW: "false"
  PHOTOPRISM_DISABLE_FACES: "false"
  PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
  PHOTOPRISM_DISABLE_VECTORS: "false"
  PHOTOPRISM_DISABLE_RAW: "false"
  PHOTOPRISM_RAW_PRESETS: "false"
  PHOTOPRISM_JPEG_QUALITY: "85"
  PHOTOPRISM_DETECT_NSFW: "false"
  PHOTOPRISM_UPLOAD_NSFW: "true"