apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-kube-state-metrics-customresourcestate-config
  namespace: prometheus
data:
  config.yaml: |
    spec:
      resources:
      - groupVersionKind:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
          version: v1beta2
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Kustomization resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - lastAppliedRevision
            source_name:
            - spec
            - sourceRef
            - name
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: helm.toolkit.fluxcd.io
          kind: HelmRelease
          version: v2beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux HelmRelease resource.
          labelsFromPath:
            chart_app_version:
            - status
            - history
            - "0"
            - appVersion
            chart_name:
            - status
            - history
            - "0"
            - chartName
            chart_ref_name:
            - spec
            - chartRef
            - name
            chart_source_name:
            - spec
            - chart
            - spec
            - sourceRef
            - name
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - history
            - "0"
            - chartVersion
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: GitRepository
          version: v1beta2
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux GitRepository resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
            url:
            - spec
            - url
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: Bucket
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Bucket resource.
          labelsFromPath:
            bucket_name:
            - spec
            - bucketName
            endpoint:
            - spec
            - endpoint
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: HelmRepository
          version: v1beta2
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux HelmRepository resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
            url:
            - spec
            - url
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: HelmChart
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux HelmChart resource.
          labelsFromPath:
            chart_name:
            - spec
            - chart
            chart_version:
            - spec
            - version
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: OCIRepository
          version: v1beta2
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux OCIRepository resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
            url:
            - spec
            - url
          name: resource_info
      - groupVersionKind:
          group: notification.toolkit.fluxcd.io
          kind: Alert
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Alert resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: notification.toolkit.fluxcd.io
          kind: Provider
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Provider resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: notification.toolkit.fluxcd.io
          kind: Receiver
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Receiver resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            suspended:
            - spec
            - suspend
            webhook_path:
            - status
            - webhookPath
          name: resource_info
      - groupVersionKind:
          group: image.toolkit.fluxcd.io
          kind: ImageRepository
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux ImageRepository resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            image:
            - spec
            - image
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: image.toolkit.fluxcd.io
          kind: ImagePolicy
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux ImagePolicy resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            source_name:
            - spec
            - imageRepositoryRef
            - name
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: image.toolkit.fluxcd.io
          kind: ImageUpdateAutomation
          version: v1beta1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux ImageUpdateAutomation resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            source_name:
            - spec
            - sourceRef
            - name
            suspended:
            - spec
            - suspend
          name: resource_info
