apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-app-volume
  namespace: photoview
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as necessary
  storageClassName: local-path